[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_options_dex = "E1TXVekuewkrgWspyhUToYeZzucutnEqyVG9eFf8WTKq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./deployer-keypair.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/**/*.ts --require ts-node/register"
